# Generated by Django 6.0.2 on 2026-02-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_8af7f1_idx',
            old_name='transactions_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_cb8cb9_idx',
            old_name='transactions_user_category_idx',
        ),
    ]
